export const materia = [
  'Matemática',
  'Lengua',
  'Literatura',
  'Lengua y Literatura',
  'Lenguas Adicionales',
  'Inglés',
  'Ciencias Naturales',
  'Biología',
  'Físico - Química',
  'Fisica',
  'Química',
  'Artes Visuales',
  'Italiano',
  'Francés',
  'Portugués',
  'Alemán',
  'Chino',
  'Formación para la vida y el trabajo',
  'Ciencias Sociales',
  'Geografía',
  'Historia',
  'Educación Física',
  'Educación Tecnológica',
  'Formación Ética y Ciudadana',
  'Música',
  'Teatro',
  'Plástica',
  'Danza',
]

export const nivel = [
  'Primario - 1',
  'Primario - 2',
  'Primario - 3',
  'Primario - 4',
  'Primario - 5',
  'Primario - 6',
  'Primario - 7',
  'Secundario - 1',
  'Secundario - 2',
  'Secundario - 3',
  'Secundario - 4',
  'Secundario - 5',
]

export const ejes = [
  'Números y Álgebra',
  'Funciones y Álgebra',
  'Geometría y Medida',
  'Estadística y Probabilidades',
  'Prácticas del Lenguaje en relación con la Literatura ',
  'Prácticas del Lenguaje y participación ciudadana',
  'Prácticas del Lenguaje en contextos de estudio de la literatura y el lenguaje',
  'Herramientas de la lengua. Uso y reflexión',
  'Ámbitos de uso de la lengua adicional',
  'Reflexión acerca del lenguaje',
  'Reflexión acerca de aspectos interculturales ',
  'Seres vivos, unidad y diversidad',
  'Panorama general de la reproducción',
  'La diversidad de los seres vivos',
  'Producción',
  'Contextualización',
  'Apreciación',
]

export const contenidos = [
  'Números Naturales',
  'Números Enteros',
  'Números Racionales positivos',
  'Números racionales',
  'Números Naturales',
  'Función lineal',
  'Ecuación de la recta',
  'Proporcionalidad inversa',
  'Triángulos',
  'Cuadriláteros',
  'Comentario de textos ',
  'Comentario de obras literarias',
  'Comunidad de lectores',
  'Producción y escucha de narraciones orales',
  'Recursos y procedimientos del discurso, el texto y la oración',
  'Modos de organización del discurso',
  'Léxico',
  'Ortografía',
  'Lectura de textos',
  'Lectura exploratoria para la búsqueda de información',
  'Lectura detenida de textos de estudio ',
  'Escritura',
  'Escritura de obras ficcionales',
  'Escritura de recomendaciones de obras leídas',
  'Análisis de textos',
  'Prevención sobre las Adicciones y el Consumo Indebido de Drogas',
  'Educación Sexual Integral',
  'Educación Digital',
  'Nivel A',
  'Nivel B',
  'Escucha de textos orales',
  'Producción de textos orales',
  'Oralidad',
  'Lectura de textos escritos',
  'Producción escrita de textos',
  'Aspectos Lingüísticos',
  'Fonología',
  'Gramática',
  'Aspectos pragmático-discursivos',
  'Aspectos lingüísticos',
  'Caracterización de los seres vivos',
  'Concepto de sistema',
  'Unidad y diversidad de funciones y estructuras',
  'Árboles de parentesco entre los seres vivos',
  'El origen de la vida',
  'Continuidad de la vida. Teoría celular',
  'Niveles de organización de la materia',
  'Biodiversidad: aspectos evolutivos',
  'Origen de células eucariotas',
  'Teoría endosimbiótica',
  'Concepto general de célula procariota y eucariota',
  'Origen de la multicelularidad',
  'Sistemas reproductores',
  'Gestación, embarazo, parto, puerperio',
  'Pubertad y la adolescencia',
  'Salud Reproductiva',
  'Salud-enfermedad',
  'Salud sexual',
  'Métodos anticonceptivos',
  'Desarrollo embrionario en humanos',
  'Materia y factura',
  'Textura',
  'Plasticidad',
  'Exploración ',
  'Experimentación',
  'Espacio-forma: distribución, organización y tensiones en el campo plástico',
  'Representación de la tridimensión',
  'Luz-color: valor, tono, saturación, luminosidad',
  'Imagen única y reproductibilidad seriada',
  'Circulación y reproducción gráfica',
  'Construcción de la mirada, percepción y conocimiento',
  'Observación y análisis de producciones',
  'Observación y análisis de las obras',
  'Patrimonio artístico',
]

export const temas = [
  'Tablas',
  'Gráficos',
  'Expresiones Algebraicas',
  'Teorema',
  'Construcción',
  'Perímetro',
  'Área',
  'Fórmulas',
  'Operaciones',
  'Equivalencias',
  'Representaciones',
  'Teorema',
  'Construcción',
  'Perímetro',
  'Área',
  'Textos Narrativos',
  'Textos expositivos',
  'Textos argumentativos',
  'Gramática',
  'Textos Ficcionales ',
  'Textos No Ficcionales',
  'Recomendación',
  'Reseñas',
  'Opinión',
  'Coherencia',
  'Cohesión',
  'Monografía',
  'Guiones',
  'Poemas',
  'Microrelatos',
  'saludar / despedirse ',
  'Presentarse',
  'Agradecer',
  'Invitar',
  'Aceptar/rechazar una invitación',
  'Información personal',
  'Pedir/ofrecer ayuda',
  'Pedir disculpas',
  'Expresar gustos y preferencias',
  'Pedir permiso',
  'Preguntar significado',
  'Describir',
  'Dar y seguir instrucciones',
  'Expresar opiniones',
  'Expresar sentimientos',
]

export const capacidades = [
  'Resolución de problemas',
  'Compartir ideas',
  'Aceptación del error',
  'Pensamiento crítico',
  'Aprender a aprender',
  'Trabajo con otros',
  'Compromiso y responsabilidad',
  'Arte, cultura y patrimonio',
  'Creatividad e innovación',
  'Participación responsable y solidaria',
  'Juventud, desarrollo y trabajo',
  'Bienestar, salud y cuidado personal',
  'Ambiente y desarrollo sostenible',
  'Expresión de ideas',
  'Técnicas de Estudio',
  'Alfabetización Digital',
  'Competencias Digitales',
  'Conocimiento Técnico',
  'Colaboración',
]
