apiVersion: apps/v1
kind: Deployment
metadata:
  name: _APP_NAME_
  namespace: _NAMESPACE_
  labels:
    app: _APP_NAME_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: _APP_NAME_
  template:
    metadata:
      labels:
        app: _APP_NAME_
    spec:
      containers:
        - name: _APP_NAME_
          image: _AWS_ACCOUNT_.dkr.ecr._AWS_DEFAULT_REGION_.amazonaws.com/_APP_NAME_-_VERSION_
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: gitlab-registry

